#use_frameworks!

target 'LPCTools_Example' do
    platform :ios,'8.0'
    inhibit_all_warnings!
    
    pod 'LPCTools', :path => '../'

  target 'LPCTools_Tests' do
    inherit! :search_paths
    
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
